### ISSUE TITLE
[BUG]: hostage_ai_enable

### ISSUE THREAD

**Issue by WasteyR** [rehlds/ReGameDLL_CS#1036]
### 🤔 What happened?

Не работает квар hostage_ai_enable.
В game_init.cfg квары bot_enable, hostage_ai_enable имеются, оба в 0 установлены. Файлы из архивов
установлены. Проблема заключается в том, что если в кс есть модели заложников из CZ, то даже при hostage_ai_enable 0, модели заложников остаются cz, на стандартные не меняются.
Если я правильно понял, то правильная работа квара должна выглядеть так: если hostage_ai_enable 0 (даже если есть в КС файлы из архива hostimprov), то заложники должны быть стандартными, используя стандартные модели заложников.
Если hostage_ai_enable 1, то модели заложников и их логика должна быть как в CZ.

### ⚠️ Meta-information

```shell
Win 10, cs steam 8684 build.
```

**Comment by dystopm** [comment]
Have you tried https://github.com/rehlds/ReGameDLL_CS/commit/f63ad678c2e4f8639d6a58376d9c8a12c090dbe7 commit?

**Comment by WasteyR** [comment]
Closed. Now fixed
