### ISSUE TITLE
Escape mode and using buttons to open doors for bots.

### ISSUE THREAD

**Issue by WasteyR** [rehlds/ReGameDLL_CS#947]
I suggest teaching bots to play es_ maps (escape mode, which was in CS beta) (at the moment, T bots do not run to the escape point) and teach bots to use the buttons (+use) to open doors on maps.

**Comment by Vaqtincha** [comment]
https://github.com/Vaqtincha/ReGameDLL_CS/commit/7e21598503935f6d6df7a040eaa6cf37a64a6a55

once did it worked great. but they didn't appreciate it

**Comment by eXPc023** [comment]
I removed func_door entities instead, which removed those doors. The map requires more fixes anyway, so I will release a version especially optimized for bots.
BTW, I fixed the escape mode, including bot support: 
[Video 1](https://www.youtube.com/watch?v=xYVWz7oHQ_4)
[Video 2](https://www.youtube.com/watch?v=KfdFFDZR730)
I will release it as soon as I complete the work on maps. (and the source code too, so you can see what I did)

> [Vaqtincha@7e21598](https://github.com/Vaqtincha/ReGameDLL_CS/commit/7e21598503935f6d6df7a040eaa6cf37a64a6a55)
> 
> once did it worked great. but they didn't appreciate it

Can you make something so bots can search for weapons on the ground? That would help in escape mode as some maps have weapons on ground for Ts to pick up.
